name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Configure CMake
      run: cmake -B _build -DBUILD_TESTS=ON
    
    - name: Build
      run: cmake --build _build
    
    - name: Test
      run: ./_build/check
