name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: sudo apt-get install -y lcov
    
    - name: Configure CMake
      run: cmake -B _build -DBUILD_TESTS=ON
    
    - name: Build
      run: cmake --build _build
    
    - name: Test
      run: ./_build/check
    
    - name: Generate coverage
      run: |
        cd _build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/third-party/*' --output-file coverage.info
    
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: _build/coverage.info
